version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: studynight
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./mount/postgres:/var/lib/postgresql/data
  studynight-backend:
    container_name: studynight-backend
    image: studynight-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      PROFILE: local
      POSTGRES_HOST: host.docker.internal
