spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studynight
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  kafka:
    consumer:
      group-id: local

security:
  cors:
    allowed-origin: "http://localhost:3000"
  token:
    access:
      secret: secret
      expiration-minutes: 30
    refresh:
      expiration-days: 14

social-login:
  google:
    client:
      client-id: "client-id"
      client-secret: "client-secret"
      scope: "openid email profile"
      redirect-uri: "http://localhost:8080/social-login/callback/provider/GOOGLE"

notification:
  alert:
    default-channel:
      type: MAIL
      address: alert@email.com

deadletter:
  server-address: "http://localhost:8080"
  redrive-token: "token"
