version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: studynight
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./mount/postgres:/var/lib/postgresql/data

  studynight-backend:
    container_name: studynight-backend
    image: ghcr.io/group-happynewyear/studynight-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      PROFILE: stage
    volumes:
      - ${HAPPYNEWYEAR_HOME}/properties/studynight-backend:/properties
