version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: studynight
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
