version: '3'

services:

  studynight-backend:
    container_name: studynight-backend-green
    image: ghcr.io/group-happynewyear/studynight-backend:${TAG}
    ports:
      - "8081:8080"
    environment:
      PROFILE: live
    volumes:
      - ./studynight-properties:/studynight-properties
      - ./logs:/logs
