package kr.happynewyear.authentication.application.producer

import com.github.josh910830.portablemq.core.producer.Producer
import com.github.josh910830.portablemq.spring.producer.SpringProducer
import kr.happynewyear.library.constant.Topics.Companion.USER_MAIL_CHANNEL_CREATE_REQUEST
import kr.happynewyear.notification.message.UserMailChannelCreateRequest

@Producer(USER_MAIL_CHANNEL_CREATE_REQUEST)
class UserMailChannelCreateRequestProducer : SpringProducer<UserMailChannelCreateRequest>
